<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <OutputType>Library</OutputType>
    <AssemblyTitle>gMKVToolNix</AssemblyTitle>
    <Description>A library to execute MKVToolNix cli utilities in .NET</Description>
    <Company>Gpower2</Company>
    <Product>gMKVToolNix</Product>
    <Copyright>Copyright © 2014-2026</Copyright>
    <AssemblyVersion>2.15.0.0</AssemblyVersion>
    <FileVersion>2.15.0.0</FileVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x86'">
    <OutputPath>bin\x86\Debug\</OutputPath>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x86'">
    <OutputPath>bin\x86\Release\</OutputPath>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <ItemGroup>
    <Compile Update="Chapters\matroskachapters.cs">
      <DependentUpon>matroskachapters.xsd</DependentUpon>
    </Compile>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Chapters\matroskachapters.xsd">
      <SubType>Designer</SubType>
    </None>
  </ItemGroup>
</Project>