<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>gMKVToolNix</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <ApplicationIcon>Images\gMkvExtractGuiIcon.ico</ApplicationIcon>
    <StartupObject>gMKVToolNix.Program</StartupObject>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x86'">
    <OutputPath>bin\x86\Debug\</OutputPath>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x86'">
    <OutputPath>bin\x86\Release\</OutputPath>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <ItemGroup>
    <Compile Update="Controls\gComboBox.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Controls\gDataGridView.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Controls\gGroupBox.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Controls\gListBox.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Controls\gTableLayoutPanel.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Controls\gTextBox.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Controls\gTreeView.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Controls\gCheckedListBox.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Controls\gRichTextBox.cs">
      <SubType>Component</SubType>
    </Compile>
    <EmbeddedResource Include="app.manifest" />
    <None Update="gmkvextract-en.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="gmkvextract-es.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="gmkvextract-de.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="gmkvextract-pt.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="gmkvextract-pt-br.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="gmkvextract-fr.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="gmkvextract-el.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="gmkvextract-zh-cn.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="gmkvextract-zh-tw.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="gmkvextract-ja.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="gmkvextract-ru.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="gmkvextract-it.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="gmkvextract-nl.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="gmkvextract-pl.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="gmkvextract-tr.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="gmkvextract-ro.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="gmkvextract-hi.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="gmkvextract-ko.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\gMKVToolNix\gMKVToolNix.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Images\gMkvExtractGuiIcon.ico" />
  </ItemGroup>
</Project>